name: Build Firefox

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

jobs:
  debian12-xfce:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: checking files
        run: |
          ls -hal
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: deserializeme/firefox-kiosk
          tags: |
            "${{github.event.inputs.tag}}"
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./firefox/
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
